insert into book (id, author, title) values (1, null, 'Company, The');
insert into book (id, author, title) values (2, null, 'American Adobo');
insert into book (id, author, title) values (3, 'Elsworth', 'Taxi Hunter (Di shi pan guan)');
insert into book (id, author, title) values (4, 'Amby', 'Man with the Gun');
insert into book (id, author, title) values (5, 'Tamas', 'They Live by Night');
insert into book (id, author, title) values (6, 'Stacie', 'Importance of Being Earnest, The');
insert into book (id, author, title) values (7, 'Kirsti', 'Train');
insert into book (id, author, title) values (8, 'Kara', 'Standing Up');
insert into book (id, author, title) values (9, 'Kariotta', 'Broken Bridges');
insert into book (id, author, title) values (10, 'Alleen', 'Frontier of the Dawn (La frontière de l''aube)');
insert into book (id, author, title) values (11, 'Moll', 'Priceless (Hors de prix)');
insert into book (id, author, title) values (12, 'Jareb', 'Man, Woman and the Wall (Kikareta onna no mirareta yoru)');
insert into book (id, author, title) values (13, 'Shayla', 'Middle of Nowhere');
insert into book (id, author, title) values (14, 'Emmy', 'C.H.U.D. II - Bud the Chud');
insert into book (id, author, title) values (15, 'Siouxie', 'Vampire Effect (The Twins Effect) (Chin gei bin)');
insert into book (id, author, title) values (16, 'Morty', 'Mon Oncle (My Uncle)');
insert into book (id, author, title) values (17, 'Freedman', 'Open Range');
insert into book (id, author, title) values (18, 'Yorke', 'Screamtime');
insert into book (id, author, title) values (19, 'Sharlene', 'The Big Cube');
insert into book (id, author, title) values (20, 'Blake', 'Heartbreak Kid, The');
insert into book (id, author, title) values (21, 'Paulette', 'Maurice');
insert into book (id, author, title) values (22, 'Julius', 'Asterix at the Olympic Games (Astérix aux jeux olympiques)');
insert into book (id, author, title) values (23, 'Joell', 'Damsel in Distress, A');
insert into book (id, author, title) values (24, 'Sebastien', 'More the Merrier, The');
insert into book (id, author, title) values (25, 'Selle', 'Loves of Pharaoh, The (Das Weib des Pharao)');
insert into book (id, author, title) values (26, 'Somerset', 'Double Dynamite');
insert into book (id, author, title) values (27, 'Tabbitha', 'Dragon Gate Inn (Dragon Inn) (Long men kezhan)');
insert into book (id, author, title) values (28, 'Rudolf', 'Treasure of the Sierra Madre, The');
insert into book (id, author, title) values (29, 'Evered', 'God is Great, I''m Not (Dieu est grand, je suis toute petite)');
insert into book (id, author, title) values (30, 'Walsh', 'Catfish');
insert into book (id, author, title) values (31, 'Renae', 'Eddie Murphy Delirious');
insert into book (id, author, title) values (32, 'Nester', 'Flight 93');
insert into book (id, author, title) values (33, 'Abby', 'Letters to Father Jacob (Postia pappi Jaakobille)');
insert into book (id, author, title) values (34, 'Debee', 'The Magic Crystal');
insert into book (id, author, title) values (35, 'Wit', 'The Hound of the Baskervilles');
insert into book (id, author, title) values (36, 'Pebrook', 'Essex Boys');
insert into book (id, author, title) values (37, 'Star', 'Bedevilled (Kim Bok-nam salinsageonui jeonmal)');
insert into book (id, author, title) values (38, 'Sue', 'Two Tars');
insert into book (id, author, title) values (39, 'Allina', 'Real Men');
insert into book (id, author, title) values (40, 'Heinrick', 'Glass Menagerie, The');
insert into book (id, author, title) values (41, 'Amabel', 'Scent of Green Papaya, The (Mùi du du xhan - L''odeur de la papaye verte)');
insert into book (id, author, title) values (42, 'Britte', 'Sanatorium');
insert into book (id, author, title) values (43, 'Raymund', 'Ellie Parker');
insert into book (id, author, title) values (44, 'Herb', '976-EVIL II');
insert into book (id, author, title) values (45, 'Maible', 'Harlan: In the Shadow of Jew Suess (Harlan - Im Schatten von Jud Süss)');
insert into book (id, author, title) values (46, 'Darbie', 'Two Bits');
insert into book (id, author, title) values (47, 'Merline', 'Sheepman, The');
insert into book (id, author, title) values (48, 'Ralf', 'Couples Retreat');
insert into book (id, author, title) values (49, 'Abbott', 'Arcana');
insert into book (id, author, title) values (50, 'Patience', 'Pollock');
insert into book (id, author, title) values (51, 'Gilli', 'Mon oncle d''Amérique');
insert into book (id, author, title) values (52, 'Hurlee', 'Husbands');
insert into book (id, author, title) values (53, 'Ax', 'Christmas in Conway');
insert into book (id, author, title) values (54, 'Jenelle', 'Halfmoon (Paul Bowles - Halbmond)');
insert into book (id, author, title) values (55, 'Joyous', 'War Tapes, The');
insert into book (id, author, title) values (56, 'Hedda', 'Magic in the Water');
insert into book (id, author, title) values (57, 'Yvor', 'Doctor at Sea');
insert into book (id, author, title) values (58, 'Alis', 'Simple Wish, A');
insert into book (id, author, title) values (59, 'Rudolf', 'Ill-Fated Love (Doomed Love) (Amor de Perdição)');
insert into book (id, author, title) values (60, 'Tiler', 'Casshern');
insert into book (id, author, title) values (61, 'Raddie', 'Forger, The');
insert into book (id, author, title) values (62, 'Joann', 'Papusza');
insert into book (id, author, title) values (63, 'Desi', 'Student Bodies');
insert into book (id, author, title) values (64, 'Mina', 'Rango');
insert into book (id, author, title) values (65, 'Ardene', 'Gloomy Sunday (Ein Lied von Liebe und Tod)');
insert into book (id, author, title) values (66, 'Barbee', 'From Dad to Son');
insert into book (id, author, title) values (67, 'Abbie', 'Bad Words');
insert into book (id, author, title) values (68, 'Willette', 'Red Beret, The');
insert into book (id, author, title) values (69, 'Leona', 'Millennium Mambo (Qian xi man po)');
insert into book (id, author, title) values (70, 'Dillie', 'Hunt, The (Jagten)');
insert into book (id, author, title) values (71, 'Janis', 'Forgive Me');
insert into book (id, author, title) values (72, 'Gunther', 'Blame It on the Bellboy');
insert into book (id, author, title) values (73, 'Gradey', 'Henry: Portrait of a Serial Killer, Part 2');
insert into book (id, author, title) values (74, 'Tull', 'The Killing Jar');
insert into book (id, author, title) values (75, 'Georgia', 'Long, Hot Summer, The');
insert into book (id, author, title) values (76, 'Steffie', 'Game of Death');
insert into book (id, author, title) values (77, 'Gaile', 'Chained Heat');
insert into book (id, author, title) values (78, 'Katharine', 'Holiday Affair');
insert into book (id, author, title) values (79, 'Konstance', 'Enquiring Minds: The Untold Story of the Man Behind the National Enquirer');
insert into book (id, author, title) values (80, 'Tracie', 'Bicycle, Spoon, Apple (Bicicleta, cullera, poma)');
insert into book (id, author, title) values (81, 'Nickola', 'Carmen Miranda: Bananas Is My Business');
insert into book (id, author, title) values (82, 'Norry', 'Deathwatch');
insert into book (id, author, title) values (83, 'Rosco', 'Stick It');
insert into book (id, author, title) values (84, 'Belinda', 'His Kind of Woman');
insert into book (id, author, title) values (85, 'Bayard', '19th Wife, The');
insert into book (id, author, title) values (86, 'Tabor', 'The Lego Movie');
insert into book (id, author, title) values (87, 'Rawley', 'Speedway');
insert into book (id, author, title) values (88, 'Ad', 'Café de Flore');
insert into book (id, author, title) values (89, 'Peria', 'Foo Fighters: Back and Forth');
insert into book (id, author, title) values (90, 'Lindy', 'Mudlark, The');
insert into book (id, author, title) values (91, 'Dre', 'Honeymooners, The');
insert into book (id, author, title) values (92, 'Kelsy', 'James Dean');
insert into book (id, author, title) values (93, 'Lorrin', 'Little Princess, A');
insert into book (id, author, title) values (94, 'Ozzie', 'Burglars, The (Le casse)');
insert into book (id, author, title) values (95, 'Gustaf', 'Next Stop, Greenwich Village');
insert into book (id, author, title) values (96, 'Janel', 'Pauline at the Beach (Pauline à la Plage)');
insert into book (id, author, title) values (97, 'Phil', 'In the Shadow of the Machine');
insert into book (id, author, title) values (98, 'Myrilla', 'Cartoonist: Jeff Smith, BONE and the Changing Face of Comics, The');
insert into book (id, author, title) values (99, 'Ronica', 'Drive Thru');
insert into book (id, author, title) values (100, 'Demetra', 'Paranormal Activity 4');
